order_site/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name="home"),
    path('login/', views.login_user, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_user, name="logout"),
    path('myinfo/', views.user_info, name="myinfo"),
    path('categories/', views.categories, name="categories"),
    path('category/<int:id>', views.show_by_category, name="category"),
    path('add_to_cart/', views.add_to_cart, name="add"),
    path('remove_from_cart/<int:id>', views.remove_from_cart, name="remove"),
    path('edit_my_info/', views.edit_my_info, name="edit"),
    path('checkout/', views.checkout, name="checkout"),
    path('cart/', views.cart, name="cart"),
    path('my_deliveries/', views.my_deliveries, name="mydeliveries"),

]

resturant_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('order_site.urls')),
    path('', include('manager_site.urls'))

]

order_site/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    username = models.CharField(blank=False, max_length=100, unique=True)
    password = models.CharField(blank=False, max_length=100)
    first_name = models.CharField(blank=False, max_length=100)
    last_name = models.CharField(blank=False, max_length=100)
    is_staff = models.BooleanField(default=False)
    email = models.EmailField(blank=False, null=True, max_length=254)

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=200)
    imageUrl = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(blank=False, max_length=200)
    price = models.IntegerField(blank=False)
    description = models.CharField(blank=False, max_length=500)
    imageUrl = models.CharField(blank=False, max_length=500)
    is_gluten_free = models.BooleanField(default=False)
    is_vegeterian = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Delivery(models.Model):
    is_delivered = models.BooleanField(default=False)
    address = models.CharField(blank=False, max_length=200)
    notes = models.CharField(max_length=500)
    created = models.DateTimeField(null=True)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    delivery = models.OneToOneField(
        Delivery, on_delete=models.CASCADE, primary_key=True)


class Items(models.Model):
    dish = models.ForeignKey(
        Dish, on_delete=models.CASCADE)
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE)
    amount = models.IntegerField(default=1)

order_site/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Category, Cart, Delivery, Dish, Items, User
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login, authenticate, logout
from datetime import datetime
import re


def home_page(request):
    return render(request, "order_site/homepage.html")


def login_user(request):
    if request.method == "POST":
        if request.POST["username"] == "" or request.POST["password"] == "":
            return render(
                request,
                "order_site/login.html",
                {"message": "*נא למלא את כל השדות"},
            )
        user = authenticate(
            request,
            username=request.POST["username"],
            password=request.POST["password"],
        )
        if user is not None:
            login(request, user)
            # מציבים את כל העגלות שנוצרו ברשימה
            carts = [c for c in user.cart_set.all()]
            cart = None
            # מציבים את העגלה האחרונה שנוצרה ובודקים האם היא עוד לא נסגרה
            if carts and carts[-1].delivery.address == "":
                cart = carts[-1]
            else:
                # יצירת עגלה עם פרטים ריקים שלאחר מכן יעודכנו
                new_cart(request)
            return redirect("categories")
        return render(
            request, "order_site/login.html", {"message": "שם משתמש או סיסמה שגויים"}
        )
    return render(request, "order_site/login.html")


def signup(request):
    if request.method == "POST":
        all_users = User.objects.all()
        for user in all_users:
            if user.username == request.POST["username"]:
                return render(
                    request, "order_site/signup.html", {"message3": "*שם משתמש תפוס"}
                )
        if (
            request.POST["username"] == ""
            or request.POST["password"] == ""
            or request.POST["first_name"] == ""
            or request.POST["last_name"] == ""
            or request.POST["email"] == ""
        ):
            return render(
                request, "order_site/signup.html", {"message": "*שדה זה הוא חובה"}
            )
        elif request.POST["password"] != request.POST["password2"]:
            return render(
                request, "order_site/signup.html", {"message2": "*הסיסמאות אינן תואמות"}
            )
        elif validate_email_address(request.POST["email"]) == False:
            return render(
                request, "order_site/signup.html", {"message4": "*אימייל לא נכון"}
            )
        else:
            new_user = User(
                username=request.POST["username"],
                password=make_password(request.POST["password"]),
                first_name=request.POST["first_name"],
                last_name=request.POST["last_name"],
                email=request.POST["email"],
            )
            new_user.save()
            return redirect("login")
    return render(request, "order_site/signup.html")


def logout_user(request):
    logout(request)
    return redirect("login")


@login_required(login_url="login")
def user_info(request):
    return render(request, "order_site/my_info.html")


@login_required(login_url="login")
def categories(request):
    all_categories = Category.objects.all()
    return render(request, "order_site/categories.html", {"categories": all_categories})


@login_required(login_url="login")
def show_by_category(request, id):
    category = Category.objects.get(id=id)
    return render(request, "order_site/show_by_category.html", {"category": category})


@login_required(login_url="login")
def remove_from_cart(request, id):
    item = Items.objects.get(id=id)
    item.delete()
    return redirect("cart")


@login_required(login_url="login")
def add_to_cart(request):
    if request.method == "POST":
        carts = [c for c in request.user.cart_set.all()]
        id = request.POST["dish"]
        dish = Dish.objects.get(id=id)
        for item in carts[-1].items_set.all():
            if item.dish.name == dish.name:
                item.amount += int(request.POST["amount"])
                item.save()
                return redirect("categories")
        else:
            new_item = Items(dish=dish, cart=carts[-1], amount=request.POST["amount"])
            new_item.save()
            return redirect("categories")


@login_required(login_url="login")
def checkout(request):
    if request.method == "POST":
        if request.POST["address"] == "" or request.POST["notes"] == "":
            return render(
                request, "order_site/checkout.html", {"message": "*שדה זה הוא חובה"}
            )
        else:
            carts = [c for c in request.user.cart_set.all()]
            cart = carts[-1]
            cart.delivery.address = request.POST["address"]
            cart.delivery.notes = request.POST["notes"]
            cart.delivery.save()
            new_cart(request)
            return redirect("mydeliveries")
    return render(request, "order_site/checkout.html")


@login_required(login_url="login")
def cart(request):
    carts = [c for c in request.user.cart_set.all()]
    cart = carts[-1]
    return render(
        request,
        "order_site/cart.html",
        {"items": cart.items_set.all(), "total": cart_amount(cart)},
    )


@login_required(login_url="login")
def edit_my_info(request):
    if request.method == "POST":
        user = request.user
        user.set_password(request.POST["password"])
        user.first_name = request.POST["first_name"]
        user.last_name = request.POST["last_name"]
        user.email = request.POST["email"]
        user.save()
        return redirect("categories")
    return render(request, "order_site/edit_my_info.html")


@login_required(login_url="login")
def my_deliveries(request):
    carts = [c for c in request.user.cart_set.all()]
    return render(request, "order_site/deliveries.html", {"carts": carts[:-1]})


def cart_amount(cart):
    items = 0
    for i in cart.items_set.all():
        items += i.dish.price * i.amount
    return items


def new_cart(request):
    delivery1 = Delivery(
        is_delivered=False, address="", notes="", created=datetime.now()
    )
    delivery1.save()
    cart = Cart(user=request.user, delivery=delivery1)
    cart.save()


def validate_email_address(email_address):
    if not re.search(
        r"^[A-Za-z0-9_!#$%&'*+\/=?`{|}~^.-]+@[A-Za-z0-9.-]+$", email_address
    ):
        print(f"The email address {email_address} is not valid")
        return False
    return True

order_site/templates/order_site/cart.html
{% extends 'layout.html' %} {% block content %}
<h1
  style="
    text-align: center;
    font-size: 50px;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    color: rgb(255, 255, 255);
    -webkit-text-stroke: 2px rgb(0, 0, 0);
  "
>
  עגלת קניות
</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">שם המנה</th>
      <th scope="col">קטגוריה</th>
      <th scope="col">כמות</th>
      <th scope="col">מחיר המנה</th>
      <th scope="row">סה״כ</th>
    </tr>
  </thead>
  <tbody>
    {% for i in items %}
    <tr>
      <td scope="row">
        <a class="nav-link" href="{% url 'remove' id=i.id %}"
          >{{i.dish.name}}
          <img
            src="https://www.iconsdb.com/icons/preview/red/delete-xxl.png"
            style="width: 20px; height: 20px"
        /></a>
      </td>
      <td>{{i.dish.category}}</td>
      <td>{{i.amount}}</td>
      <td>{{i.dish.price}}</td>
      <td></td>
    </tr>
    {% endfor %}
    <tr style="border: 1px solid rgb(216, 206, 206)">
      <td scope="row"></td>
      <td></td>
      <td></td>
      <td></td>
      <td>{{total}}</td>
    </tr>
  </tbody>
</table>
<a href="{% url 'checkout' %}" class="btn btn-primary position-absolute end-0"
  >לתשלום</a
>
{% endblock %}

order_site/templates/order_site/categories.html
{% extends 'layout.html' %} {% block content %}

<div class="container text-center">
  <div class="row">
    <h1
      style="
        font-size: 92px;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color: rgb(255, 255, 255);
        -webkit-text-stroke: 2px rgb(0, 0, 0);
      "
    >
      קטגוריות
    </h1>
  </div>
  <div class="row">
    {% for category in categories %}
    <div class="col">
      <div
        class="card shadow p-3 mb-5 bg-body-tertiary rounded"
        style="width: 18rem"
      >
        <a href="{% url 'category' id=category.id %}"
          ><img
            src="{{category.imageUrl}}"
            class="card-img-top"
            style="height: 150px; width: 250px"
        /></a>
        <div class="card-body">
          <h5 class="card-title">{{category.name}}</h5>
          <a href="{% url 'category' id=category.id %}" class="btn btn-primary"
            >לחץ לפתיחה</a
          >
          {% if request.user.is_staff%}
          <a href="{% url 'edit_cat' id=category.id %}"
            ><img
              src="https://cdn-icons-png.flaticon.com/512/1827/1827951.png"
              style="height: 20px; width: 20px"
          /></a>
          <a href="{% url 'del_cat' id=category.id %}"
            ><img
              src="https://www.iconsdb.com/icons/preview/red/delete-xxl.png"
              style="height: 20px; width: 20px"
          /></a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

order_site/templates/order_site/checkout.html
{% extends 'layout.html' %} {% block content %}
<div class="card text-center">
  <div class="card-header">
    <h2>אנא הזינו את פרטי המשלוח</h2>
  </div>
  <div class="card-body">
    <form action="{% url 'checkout' %}" method="POST">
      {%csrf_token%}
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="address"
          placeholder="כתובת"
        />
      </div>
      <div style="color: red">{{message}}</div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="notes"
          placeholder="הערות"
        />
      </div>
      <div style="color: red">{{message}}</div>
      <div>
        <button type="submit" class="btn btn-primary">אישור הזמנה</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

order_site/templates/order_site/deliveries.html
{% extends 'layout.html' %} {% block content %}
<h1
  style="
    text-align: center;
    font-size: 50px;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    color: rgb(255, 255, 255);
    -webkit-text-stroke: 2px rgb(0, 0, 0);
  "
>
המשלוחים שלי</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">מספר הזמנה</th>
      <th scope="col">כתובת הזמנה</th>
      <th scope="col">הזמנה הגיע</th>
      <th scope="col">הערות נוספות</th>
    </tr>
  </thead>
  <tbody>
    {% for cart in carts %}
    <tr>
      <td scope="row">{{cart.delivery.id}}</td>
      <td>{{cart.delivery.address}}</td>

      {% if cart.delivery.is_delivered %}
      <td>הושלמה</td>
      {% else %}
      <td>
        במשלוח {% if request.user.is_superuser %}
        <form
          action="{% url 'confirm_del' id=cart.delivery.id %}"
          method="POST"
        >
          {%csrf_token%}
          <input type="checkbox" name="is_delivered" />
          <button type="submit">אישור הגעה</button>
        </form>
        {% endif %}
      </td>
      {% endif %}

      <td>{{cart.delivery.notes}}</td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

order_site/templates/order_site/edit_my_info.html
{% extends 'layout.html' %} {% block content %}
<div class="card text-center">
  <div class="card-body">
    <form action="{% url 'edit' %}" method="POST">
      {%csrf_token%}
      <div>
        <input
          type="password"
          class="form-control text-center"
          name="password"
          placeholder="סיסמה"
          value="{{user.password}}"
        />
      </div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="first_name"
          placeholder="שם פרטי"
          value="{{user.first_name}}"
        />
      </div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="last_name"
          placeholder="שם משפחה"
          value="{{user.last_name}}"
        />
      </div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="email"
          placeholder="כתובת אימייל"
          value="{{user.email}}"
        />
      </div>
        <button type="submit" class="btn btn-primary">אישור</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

order_site/templates/order_site/homepage.html
{% extends 'layout.html' %} {% block content %}
<div
  style="
    background-image: url('https://images.unsplash.com/photo-1600891964599-f61ba0e24092?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80');
    background-size: cover;
    width: 100vw;
    height: 100vh;
  "
>
  <div
    style="
      background-color: rgb(0, 0, 0); /* Fallback color */
      background-color: rgba(0, 0, 0, 0.4); /* Black w/opacity/see-through */
      color: black;
      font-weight: bold;
      border: 3px solid rgb(248, 249, 250) k;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 2;
      width: 80%;
      padding: 20px;
      text-align: center;
    "
  >
    <h1
      style="
        font-size: 92px;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color: rgb(237, 234, 202);
        -webkit-text-stroke: 2px rgb(0, 0, 0);
      "
    >
      ברוכים הבאים
    </h1>
  </div>
</div>

{% endblock %}

order_site/templates/order_site/login.html
{% extends 'layout.html' %} {% block content %} {% if message %}
<div
  class="p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3"
>
  {{message}}
</div>
{% endif %}
<div class="card text-center">
  <div class="card-body">
    <div class="card-header">
      <h3>כניסת לקוח:</h3>
    </div>
    <form action="{% url 'login' %}" method="POST">
      {%csrf_token%}
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="username"
          placeholder="שם משתמש"
        />
      </div>
      <div>
        <input
          type="password"
          class="form-control text-center"
          name="password"
          placeholder="סיסמה"
        />
      </div>

      <button type="submit" class="btn btn-primary">אישור</button>
    </form>
  </div>
</div>

{% endblock %}

order_site/templates/order_site/my_info.html
{% extends 'layout.html' %} {% block content %}
<div class="card text-center">
  <div class="card-header">הפרטים שלי</div>
  <div class="card-body">
    <h4 class="card-title">שם משתמש: {{user.username}}</h4>
    <p class="card-text">שם פרטי: {{user.first_name}}</p>
    <p class="card-text">שם משפחה: {{user.last_name}}</p>
    <p class="card-text">אימייל: {{user.email}}</p>
    {% if request.user.is_staff %}
    <p class="card-text">דרגת הרשאה: הנהלה</p>
    {% else %}
    <p class="card-text">דרגת הרשאה: לקוח רשום</p>
    {% endif %}
    <a href="{% url 'edit' %}" class="btn btn-primary">עריכת הפרטים שלי</a>
  </div>
</div>
{% endblock %}

order_site/templates/order_site/show_by_category.html
{% extends 'layout.html' %} {% block content %}

<div class="container text-center">
  <div class="row">
    <h1
      style="
        font-size: 92px;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color: rgb(255, 255, 255);
        -webkit-text-stroke: 2px rgb(0, 0, 0);
      "
    >
      {{category.name}}
    </h1>
  </div>

  <div class="row">
    {% for dish in category.dish_set.all %}
    <div class="col">
      <form action="{% url 'add' %}" method="POST">
        {%csrf_token%}
        <div
          class="card shadow p-3 mb-5 bg-body-tertiary rounded"
          style="width: 18rem"
        >
          <img
            src="{{dish.imageUrl}}"
            class="card-img-top"
            style="height: 160px; width: 250px"
            alt="..."
          />
          <div class="card-body">
            <h2 class="card-title">{{dish.name}}</h2>
            <h5 class="card-text">מחיר: {{dish.price}}&#8362;</h5>
            <p class="card-text">{{dish.description}}</p>
            <div>
              {% if dish.is_gluten_free == True %}
              <img
                src="https://static.vecteezy.com/system/resources/previews/000/343/969/original/vector-gluten-free-icon.jpg"
                style="width: 75px; height: 75px"
              />
              {% else %}
              <img
                src="https://www.stickergizmo.com/media/catalog/product/cache/image/265x265/beff4985b56e3afdbeabfc89641a4582/g/l/glutenallergen.png"
                style="width: 75px; height: 75px"
              />
              {% endif %} {% if dish.is_vegeterian == True %}
              <img
                src="https://img.freepik.com/premium-vector/vegan-logo-design-vegan-badge-design_526569-858.jpg?w=2000"
                style="width: 75px; height: 75px"
              />
              {% else %}
              <img
                src="https://thecrumbyvegan.files.wordpress.com/2019/12/notvegananymore.jpg?w=660"
                style="width: 75px; height: 75px"
              />
              {% endif %}
            </div>
            <input type="number" name="amount" min="1" max="100" value="1" />
            <button
              class="btn btn-primary"
              type="submit"
              name="dish"
              value="{{dish.id}}"
            >
              הוספה לעגלה
            </button>
            {% if request.user.is_staff %}
            <a href="{% url 'edit_dish' id=dish.id %}"
              ><img
                src="https://cdn-icons-png.flaticon.com/512/1827/1827951.png"
                style="height: 20px; width: 20px"
            /></a>
            <a href="{% url 'del_dish' id=category.id %}"
              ><img
                src="https://www.iconsdb.com/icons/preview/red/delete-xxl.png"
                style="height: 20px; width: 20px"
            /></a>
            {% endif %}
          </div>
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
  <div class="row">
    <div class="col">
      <a href="{% url 'categories' %}" class="btn btn-primary"
        >חזרה לתפריט הראשי</a
      >
    </div>
  </div>
</div>

{% endblock %}

order_site/templates/order_site/signup.html
{% extends 'layout.html' %} {% block content %}
<div class="card text-center">
  <div class="card-header">
    <h3>הרשמה:</h3>
  </div>
  <div class="card-body">
    <form action="{% url 'signup' %}" method="POST">
      {%csrf_token%}
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="username"
          placeholder="שם משתמש"
        />
        <div style="color: red">{{message}}</div>
        <div style="color: red">{{message3}}</div>
      </div>
      <div>
        <input
          type="password"
          class="form-control text-center"
          name="password"
          placeholder="סיסמה"
        />
        <div style="color: red">{{message}}</div>
      </div>
      <div>
        <input
          type="password"
          class="form-control text-center"
          name="password2"
          placeholder="אשר סיסמה"
        />
        <div style="color: red">{{message}}</div>
        <div style="color: red">{{message2}}</div>
      </div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="first_name"
          placeholder="שם פרטי"
        />
        <div style="color: red">{{message}}</div>
      </div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="last_name"
          placeholder="שם משפחה"
        />
        <div style="color: red">{{message}}</div>
      </div>
      <div>
        <input
          type="text"
          class="form-control text-center"
          name="email"
          placeholder="כתובת אימייל"
        />
        <div style="color: red">{{message}}</div>
        <div style="color: red">{{message4}}</div>
      </div>
      <button type="submit" class="btn btn-primary">הרשמה</button>
    </form>

    {% endblock %}
  </div>
</div>